<a href="https://colab.research.google.com/github/routb68/hdlc/blob/main/lda_pca_re_error.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Loading

In [ ]:
import pickle
with open('/content/drive/MyDrive/Fairness in machine learning/HLDC   LDA preWork/df.pkl', 'rb') as file:
    df = pickle.load(file)

In [ ]:
df

label                                           sentence  word_count  \
0         1     ['अभियुक्त इस मामले में जेल में निरुद्ध है। ']           9   
1         0  ['जमानत प्रार्थना पत्र के समर्थन में रहमीना पत...         485   
2         0  ['संक्षेप में अभियोजन कथानक इस प्रकार है कि वा...         517   
3         0  ['जमानत प्रार्थना-पत्र के समर्थन में शपथ-पत्र ...         269   
4         0  ['अभियोजन कहानी के अनुसार वादी मुकदमा पुलिस उप...         625   
...     ...                                                ...         ...   
9995      1  ['04.03.2021यह जमानत प्रार्थना पत्र प्रार्थी /...         604   
9996      0  ['अभियुक्तगण न्यायिक अभिरक्षा में जेल में निरू...         461   
9997      1  ['23.10.2020पत्रावली पेश हुई । प्रार्थी / अभिय...         237   
9998      0  ['इस आवेदन के साथ अभियुक्ता की रिश्तेदार सुलेख...         167   
9999      0  ['फ्ठार्थीगण / अभियुक्तगण न्यायिक अभिरक्षा में...          68   

                                         text_processed  \
0     [[, ', अभियुक्त, इस, मामले, में, जेल, में, निर...   
1     [[, ', जमानत, प्रार्थना, पत्र, के, समर्थन, में...   
2     [[, ', संक्षेप, में, अभियोजन, कथानक, इस, प्रका...   
3     [[, ', जमानत, प्रार्थना, -, पत्र, के, समर्थन, ...   
4     [[, ', अभियोजन, कहानी, के, अनुसार, वादी, मुकदम...   
...                                                 ...   
9995  [[, ', 04032021यह, जमानत, प्रार्थना, पत्र, प्र...   
9996  [[, ', अभियुक्तगण, न्यायिक, अभिरक्षा, में, जेल...   
9997  [[, ', 23102020पत्रावली, पेश, हुई, ।, प्रार्थी...   
9998  [[, ', इस, आवेदन, के, साथ, अभियुक्ता, की, रिश्...   
9999  [[, ', फ्ठार्थीगण, अभियुक्तगण, न्यायिक, अभिरक्...   

                                    text_processed_stop  \
0                       [अभियुक्त, मामले, जेल, निरुद्ध]   
1     [जमानत, प्रार्थना, पत्र, समर्थन, रहमीना, पत्नी...   
2     [संक्षेप, अभियोजन, कथानक, प्रकार, वादी, मुकदमा...   
3     [जमानत, प्रार्थना, पत्र, समर्थन, शपथ, पत्र, इम...   
4     [अभियोजन, कहानी, अनुसार, वादी, मुकदमा, पुलिस, ...   
...                                                 ...   
9995  [04032021यह, जमानत, प्रार्थना, पत्र, प्रार्थी,...   
9996  [अभियुक्तगण, न्यायिक, अभिरक्षा, जेल, निरूद्ध, ...   
9997  [23102020पत्रावली, पेश, प्रार्थी, अभियुक्त, वि...   
9998  [आवेदन, अभियुक्ता, रिश्तेदार, सुलेखा, नाम, काश...   
9999  [फ्ठार्थीगण, अभियुक्तगण, न्यायिक, अभिरक्षा, अभ...   

      word_count_text_processed_stop  \
0                                  4   
1                                292   
2                                306   
3                                154   
4                                363   
...                              ...   
9995                             397   
9996                             273   
9997                             114   
9998                              93   
9999                              30   

                       text_processed_stop_rem_mostfreq  \
0                                 [मामले, जेल, निरुद्ध]   
1     [समर्थन, रहमीना, पत्नी, फैय्याज, शपथपत्र, आशय,...   
2     [संक्षेप, कथानक, प्रकार, पाण्डेयपुत्र, स्व0, द...   
3     [समर्थन, शपथ, इमरान, पुत्रमुखिया, उर्फ, मुजाफि...   
4     [कहानी, अनुसार, उपनिरीक्षक, श्रीअरविन्द, 24062...   
...                                                 ...   
9995  [द्वाराउपरोक्त, संख्या, ह़ै, शपथ, समर्थित, मय,...   
9996  [न्यायिक, अभिरक्षा, जेल, निरूद्ध, कथानक, अनुसा...   
9997  [पेश, समक्ष, यहतक, प््रार्थीअभियुक्त, निर्दोष,...   
9998  [आवेदन, अभियुक्ता, रिश्तेदार, सुलेखा, काशपथपत्...   
9999  [न्यायिक, अभिरक्षा, कहाहै, प््रार्थीगण, निर्दो...   

      word_count_text_processed_stop_rem_mostfreq  \
0                                               3   
1                                             214   
2                                             205   
3                                              99   
4                                             303   
...                                           ...   
9995                                          269   
9996                                 

In [ ]:
data, data_label = df['sentence_cleaned_split'], df['label']

In [ ]:
for i in range(200,206):
  print(i)
  print(data[i])
  print(data_label[i])
  print(" ")

200
['संक्षेप', 'कथानक', 'अनुसार', 'कुमारलुलस्यान', 'खेत', 'ग्राम', 'नरकहवां', 'तहसील', 'खड्डा', 'स्थित', 'खातेदार', 'उसकेअन्य', 'ग्राम', 'स्थित', 'खेत', 'चकबन्दी', 'चक', 'नं०', '246', 'प्रदिष्ट', 'जिसमेंदो', 'चक', 'प्रस्तावित', 'पहला', 'चक', 'आराजी', 'नं०', '1149', '524', 'एकड़', 'चकआराजी', 'नं०', '952', '169', 'एकड़', 'प्रदिष्ट', 'आराजीयात', 'भूमिधरी', 'तथाउसके', 'जोत', 'स्वामित्व', 'विवाद', '05042019', 'कोधोखाधड़ी', 'जालसाजी', 'करे', 'चक', 'नम्बर', '246', 'प्रस्तावित', 'द्वितीय', 'चकको', 'स्वामित्व', 'अरूण', 'उर्फ', 'नेजानबूझकर', 'सहयोगी', 'मददगार', 'सहयोग', 'आराजी', 'बताते', 'दोकिता', 'बैनामा', 'पहला', 'बैनामा', 'उपरोक्त', 'लोगों', 'आराजी', 'नं०', '246', 'चक', 'केआराजी', 'नं०', '1149,1150,1151,1155,1158', '1159', 'बने', 'चक', '293', '2एकड़', 'बैनामा', 'शान्ति', 'दिनांक05042019', 'जानबुझकर', 'धोखाधड़ी', 'जालसाजी', 'लाभपहुँचाने', 'हानि', 'पहुँचाने', 'इरादे', 'बैनामा', 'दिनांक06042019', 'उपरोक्त', 'विक्रेता', 'अरूण', 'उर्फजयप्रकाश', 'पुनः', 'चक', '246', 'चक', 'गाटा', 'संख्या', '1150',

In [ ]:
muslim = {"अब्दुल", "अहमद", "आरिफ", "खां", "खालिद", "नदीम", "मुस्लिम", "मोहम्मद", "रिजवान", "सलीम" }
hindu = {"अमरजीत", "आर्य", "आशीष", "ओमकार", "किशोर", "कुलदीप", "जयराम", "धीरेन्द्र", "नितिन", "मुलायम", "राजपूत", "रामानन्द", "विजयपाल", "विमलेश", "श्रीराम"}

In [ ]:
gt_data,gt_label,gt_reli = [],[],[]

In [ ]:
num_hindu, num_muslim = 0,0
for i in range(10000):
  for x in data[i]:
     for y in muslim:
      if(x==y):
        gt_data.append(data[i]);
        gt_label.append(data_label[i])
        gt_reli.append(1)
        num_muslim += 1
        break;


     for y in hindu:
      if(x==y):
        gt_data.append(data[i]);
        gt_label.append(data_label[i])
        gt_reli.append(2)
        num_hindu += 1
        break;

In [ ]:
print(num_hindu)
print(num_muslim)

1057
1722


In [ ]:
org_gt_data,org_gt_label,org_gt_reli =gt_data,gt_label,gt_reli

In [ ]:
gt_data,gt_label,gt_reli = [], [], []

In [ ]:
cnt1, cnt2 = 0, 0

In [ ]:
for i in range(len(org_gt_data)):
  if(org_gt_reli[i]==1 and cnt1<1010):
    gt_data.append(org_gt_data[i])
    gt_label.append(org_gt_label[i])
    gt_reli.append(org_gt_reli[i])
    cnt1+=1;
  elif (org_gt_reli[i]==2 and cnt2<1010):
    gt_data.append(org_gt_data[i])
    gt_label.append(org_gt_label[i])
    gt_reli.append(org_gt_reli[i])
    cnt2+=1;

In [ ]:
print(cnt1)
print(cnt2)
print(len(gt_data))
len(org_gt_data)

1010
1010
2020


2779

#LDA

In [ ]:
import gensim
from gensim.models.ldamodel import LdaModel
from gensim.corpora.dictionary import Dictionary
from gensim import corpora
text_corpus = gt_data
dictionary = corpora.Dictionary(text_corpus)
common_corpus = [dictionary.doc2bow(x) for x in text_corpus]

In [ ]:
def lda_creation(num_topic,n_word):
  lda = LdaModel(common_corpus, num_topics=num_topic,minimum_probability=0)
  lda_vector = []
  for text in text_corpus:
    text_vec = [dictionary.doc2bow(text)]
    text_topics = lda[text_vec]

    temp_topic = []
    for topic in text_topics:
      temp_topic.append(topic)

    lda_vector.append(temp_topic)

  x_tp = lda.show_topics(num_topics= num_topic, num_words=n_word,formatted=False)
  topics_words = [(tp[0], [wd[0] for wd in tp[1]]) for tp in x_tp]
  # for topic,words in topics_words:
  #   print(str(topic)+ "::"+ str(words))
  #   print()
  # # print()
  topic_wds = []
  for i in range(num_topic):
    tp_wd = list(w for w,_ in lda.show_topic(topicid = i,topn=n_word))
    temp_wds = []
    for x in tp_wd:
      x1 = int(x)
      temp_wds.append(dictionary.get((x1)))
    topic_wds.append(temp_wds)

  return lda_vector,topic_wds

In [ ]:
# x1 = lda_creation(30)

In [ ]:
# for i in range(200,204):
#   print(x1[i])

# topics num 30 - 100

In [ ]:
vec_lda, top_word = [],[]
n = 5
for i in range(30,100,10):
  x1,x2 = lda_creation(i,5) # x1==lda vector, x2== top n words of lda
  vec_lda.append(x1)
  top_word.append(x2)

In [ ]:
# import csv
# from google.colab import files

In [ ]:
# import pandas as pd
# df = pd.DataFrame(top_word)
# writer = pd.ExcelWriter('test.xlsx')
# df.to_excel(writer, sheet_name='welcome', index=False)
# writer.save()

In [ ]:
print(len(vec_lda))

7


In [ ]:
t30_lda_vec = vec_lda[0]

#PCA Testing

In [ ]:
import numpy as np

In [ ]:
pca_data = np.zeros((2020,30))
for i in range(2020):
  for j in range(30):
    pca_data[i][j] = t30_lda_vec[i][0][j][1]

In [ ]:
pca_data.shape

(2020, 30)

In [ ]:
mean_data = np.zeros((1,30))
for i in range(2020):
  mean_data += pca_data[i]

In [ ]:
print(np.sum(mean_data))
mean_data /=2020

2020.0000037370082


In [ ]:
print(mean_data[0])
np.sum(mean_data)

[0.03854033 0.07184116 0.01331519 0.02962416 0.07656918 0.00852613
 0.04062831 0.06608127 0.02679896 0.03485669 0.01625917 0.00810354
 0.0296917  0.1037322  0.01739199 0.04177427 0.00814543 0.04187732
 0.05808601 0.02504627 0.01701205 0.01107102 0.0077005  0.02012582
 0.01780644 0.02417913 0.05027943 0.04682488 0.01800749 0.03010396]


1.0000000018500041

In [ ]:
for i in range(2020):
  for j in range(30):
    pca_data[i][j] -= mean_data[0][j]

In [ ]:
print(pca_data[0])
print(pca_data.shape)

[ 0.07069269  0.04569327  0.23849846 -0.02949082 -0.07643583 -0.00839278
 -0.04049496 -0.06594793  0.19357005 -0.03472334 -0.01612582 -0.0079702
 -0.02955835 -0.10359885 -0.01725865  0.03847205 -0.00801208 -0.04174398
 -0.05795266 -0.02491292 -0.01687871 -0.01093767 -0.00756716  0.08650777
 -0.0176731  -0.02404578  0.06082356 -0.04669153 -0.01787415 -0.02997061]
(2020, 30)


In [ ]:
cov_mat = np.cov(np.transpose(pca_data))
# print(cov_mat.shape)
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

In [ ]:
print(eig_vals.shape)
print(eig_vecs.shape)

(30,)
(30, 30)


In [ ]:
idx = eig_vals.argsort()[::-1]
eig_vals = eig_vals[idx]
eig_vecs = eig_vecs[:,idx]

In [ ]:
eig_vals

array([5.25194258e-02, 4.45271557e-02, 3.20568308e-02, 2.90528273e-02,
       2.76563558e-02, 2.63486951e-02, 2.49352936e-02, 2.32784830e-02,
       2.07875932e-02, 1.99580593e-02, 1.91872224e-02, 1.77103990e-02,
       1.58284126e-02, 1.47971113e-02, 1.45208396e-02, 1.37786235e-02,
       1.30631053e-02, 1.23164090e-02, 1.23040023e-02, 1.13843952e-02,
       1.11259015e-02, 7.89145455e-03, 6.93843321e-03, 5.62132130e-03,
       4.95457949e-03, 4.28436213e-03, 3.76891378e-03, 3.27367565e-03,
       2.01298582e-03, 3.72972053e-17])

In [ ]:
eig_vecs[0]

array([-0.03030379,  0.07991934, -0.0931171 ,  0.00459033,  0.00122808,
        0.09096787, -0.21831279,  0.60619381, -0.62845356, -0.04197987,
        0.04139414,  0.26293607, -0.16360997,  0.00772856,  0.0711057 ,
       -0.12690092,  0.04164761, -0.03193617, -0.02299226, -0.01798431,
        0.00280088, -0.05876919, -0.0104731 ,  0.03424554,  0.0364846 ,
       -0.03132738, -0.02164267, -0.00561065,  0.02335414,  0.18257419])

In [ ]:
multiplier = np.dot(np.transpose(pca_data[0]),eig_vecs[0])
recon_data = multiplier* eig_vecs[0]

In [ ]:
a = np.linalg.norm(recon_data - pca_data[0])
print(a)

0.34504853005442065


In [ ]:
pca_data[0]

array([ 0.07069269,  0.04569327,  0.23849846, -0.02949082, -0.07643583,
       -0.00839278, -0.04049496, -0.06594793,  0.19357005, -0.03472334,
       -0.01612582, -0.0079702 , -0.02955835, -0.10359885, -0.01725865,
        0.03847205, -0.00801208, -0.04174398, -0.05795266, -0.02491292,
       -0.01687871, -0.01093767, -0.00756716,  0.08650777, -0.0176731 ,
       -0.02404578,  0.06082356, -0.04669153, -0.01787415, -0.02997061])

# PCA and Reconstruction Error

In [132]:
def re_error(n,x_data,topic_num):
  total_cost, hindu_cost, muslim_cost = 0,0,0

  #mean calculation
  mean_data = np.zeros((1,topic_num))
  for i in range(2020):
    mean_data += pca_data[i]
  mean_data /=2020
  for i in range(2020):
    for j in range(30):
      pca_data[i][j] -= mean_data[0][j]

  #pca calculation
  cov_mat = np.cov(np.transpose(pca_data))
  eig_vals, eig_vecs = np.linalg.eig(cov_mat)
  idx = eig_vals.argsort()[::-1]
  eig_vals = eig_vals[idx]
  eig_vecs = eig_vecs[:,idx]

  # reconstruction error calculation
  x=0
  for i in range(2020):
    x = 0
    z = np.zeros((1,topic_num))
    for j in range(n):
      z += (((np.dot(np.transpose(pca_data[i]),eig_vecs[j]))) * eig_vecs[j])

    x += (np.linalg.norm (z - pca_data[i]))

    total_cost += x
    if gt_reli[i]==1:
      muslim_cost += x
    else :
      hindu_cost += x
  # print(total_cost)

  total_cost /= 2020
  hindu_cost /= 1010
  muslim_cost /= 1010

# multiplier = np.dot(np.transpose(pca_data[0]),eig_vecs[0])
# recon_data = multiplier* eig_vecs[0]
# a = np.linalg.norm(recon_data - pca_data[0])



  return total_cost, hindu_cost, muslim_cost

In [133]:
reconstruction_error_total, reconstruction_error_hindu, reconstruction_error_muslim = [], [], []

for i in range(1,20):
  re_t,re_h,re_m = re_error(i,pca_data,30)
  reconstruction_error_total.append(re_t)
  reconstruction_error_hindu.append(re_h)
  reconstruction_error_muslim.append(re_m)
  # print()

In [135]:
print(reconstruction_error_muslim)
print(reconstruction_error_total)
print(reconstruction_error_hindu)

[0.6959136745109517, 0.6787947831688879, 0.6656372681650272, 0.6628286520182786, 0.6421725452586289, 0.6188335149948642, 0.6096939154553851, 0.604909071561841, 0.5836823902640307, 0.5637332302532267, 0.5514376005186218, 0.5328038187396481, 0.5254603072624895, 0.5049760659858679, 0.4741558204803775, 0.45200035571065994, 0.4452645666561409, 0.43130478520596316, 0.42188510670279405]
[0.6642343553407438, 0.6486315268284827, 0.6286723283996686, 0.6271303590511368, 0.604027672032773, 0.58606689579918, 0.5753688874226573, 0.5713387851329466, 0.549354577222096, 0.5334005792498183, 0.5259877256665934, 0.5123299896280458, 0.4998956132107794, 0.4787122731746023, 0.4510543225481554, 0.433019464888626, 0.4238914468845374, 0.40739723900811003, 0.4005331105529153]
[0.6325550361705352, 0.618468270488077, 0.5917073886343083, 0.591432066083993, 0.5658827988069155, 0.5533002766034953, 0.5410438593899272, 0.5377684987040511, 0.5150267641801618, 0.5030679282464084, 0.5005378508145631, 0.49185616051644226, 