<a href="https://colab.research.google.com/github/routb68/hdlc/blob/main/lda_27Sept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Loading


In [1]:
import pickle
with open('/content/drive/MyDrive/Fairness in machine learning/HLDC   LDA preWork/df.pkl', 'rb') as file:
    df = pickle.load(file)

In [2]:
df

label                                           sentence  word_count  \
0         1     ['अभियुक्त इस मामले में जेल में निरुद्ध है। ']           9   
1         0  ['जमानत प्रार्थना पत्र के समर्थन में रहमीना पत...         485   
2         0  ['संक्षेप में अभियोजन कथानक इस प्रकार है कि वा...         517   
3         0  ['जमानत प्रार्थना-पत्र के समर्थन में शपथ-पत्र ...         269   
4         0  ['अभियोजन कहानी के अनुसार वादी मुकदमा पुलिस उप...         625   
...     ...                                                ...         ...   
9995      1  ['04.03.2021यह जमानत प्रार्थना पत्र प्रार्थी /...         604   
9996      0  ['अभियुक्तगण न्यायिक अभिरक्षा में जेल में निरू...         461   
9997      1  ['23.10.2020पत्रावली पेश हुई । प्रार्थी / अभिय...         237   
9998      0  ['इस आवेदन के साथ अभियुक्ता की रिश्तेदार सुलेख...         167   
9999      0  ['फ्ठार्थीगण / अभियुक्तगण न्यायिक अभिरक्षा में...          68   

                                         text_processed  \
0     [[, ', अभियुक्त, इस, मामले, में, जेल, में, निर...   
1     [[, ', जमानत, प्रार्थना, पत्र, के, समर्थन, में...   
2     [[, ', संक्षेप, में, अभियोजन, कथानक, इस, प्रका...   
3     [[, ', जमानत, प्रार्थना, -, पत्र, के, समर्थन, ...   
4     [[, ', अभियोजन, कहानी, के, अनुसार, वादी, मुकदम...   
...                                                 ...   
9995  [[, ', 04032021यह, जमानत, प्रार्थना, पत्र, प्र...   
9996  [[, ', अभियुक्तगण, न्यायिक, अभिरक्षा, में, जेल...   
9997  [[, ', 23102020पत्रावली, पेश, हुई, ।, प्रार्थी...   
9998  [[, ', इस, आवेदन, के, साथ, अभियुक्ता, की, रिश्...   
9999  [[, ', फ्ठार्थीगण, अभियुक्तगण, न्यायिक, अभिरक्...   

                                    text_processed_stop  \
0                       [अभियुक्त, मामले, जेल, निरुद्ध]   
1     [जमानत, प्रार्थना, पत्र, समर्थन, रहमीना, पत्नी...   
2     [संक्षेप, अभियोजन, कथानक, प्रकार, वादी, मुकदमा...   
3     [जमानत, प्रार्थना, पत्र, समर्थन, शपथ, पत्र, इम...   
4     [अभियोजन, कहानी, अनुसार, वादी, मुकदमा, पुलिस, ...   
...                                                 ...   
9995  [04032021यह, जमानत, प्रार्थना, पत्र, प्रार्थी,...   
9996  [अभियुक्तगण, न्यायिक, अभिरक्षा, जेल, निरूद्ध, ...   
9997  [23102020पत्रावली, पेश, प्रार्थी, अभियुक्त, वि...   
9998  [आवेदन, अभियुक्ता, रिश्तेदार, सुलेखा, नाम, काश...   
9999  [फ्ठार्थीगण, अभियुक्तगण, न्यायिक, अभिरक्षा, अभ...   

      word_count_text_processed_stop  \
0                                  4   
1                                292   
2                                306   
3                                154   
4                                363   
...                              ...   
9995                             397   
9996                             273   
9997                             114   
9998                              93   
9999                              30   

                       text_processed_stop_rem_mostfreq  \
0                                 [मामले, जेल, निरुद्ध]   
1     [समर्थन, रहमीना, पत्नी, फैय्याज, शपथपत्र, आशय,...   
2     [संक्षेप, कथानक, प्रकार, पाण्डेयपुत्र, स्व0, द...   
3     [समर्थन, शपथ, इमरान, पुत्रमुखिया, उर्फ, मुजाफि...   
4     [कहानी, अनुसार, उपनिरीक्षक, श्रीअरविन्द, 24062...   
...                                                 ...   
9995  [द्वाराउपरोक्त, संख्या, ह़ै, शपथ, समर्थित, मय,...   
9996  [न्यायिक, अभिरक्षा, जेल, निरूद्ध, कथानक, अनुसा...   
9997  [पेश, समक्ष, यहतक, प््रार्थीअभियुक्त, निर्दोष,...   
9998  [आवेदन, अभियुक्ता, रिश्तेदार, सुलेखा, काशपथपत्...   
9999  [न्यायिक, अभिरक्षा, कहाहै, प््रार्थीगण, निर्दो...   

      word_count_text_processed_stop_rem_mostfreq  \
0                                               3   
1                                             214   
2                                             205   
3                                              99   
4                                             303   
...                                           ...   
9995                                          269   
9996                                 

In [3]:
data, data_label = df['sentence_cleaned_split'], df['label']

In [4]:
for i in range(100,106):
  print(i)
  print(data[i])
  print(data_label[i])
  print(" ")

100
['संलग्न', 'शपथपत्रमें', 'सत्रन्यायालय', 'उच्च', 'विचाराधीन', 'खारिज', 'संक्षेप', 'कथानक', 'प्रकार', '27', '11', '2019', 'कोप्रभारी', 'निरीक्षक', 'अनन्त', 'मय', 'कर्मचारीगण', 'ग्राम', 'खमरिया', 'जमीनी', 'कब्जेदारी', 'विवाद', 'मौके', 'पहुँचा', 'पक्ष', 'जयवीर', 'पुत्रमथुरी', 'रामभजन', 'जयवीर', 'राममोहन', 'रविन्द्र', 'ओमेन्द्र', 'अवधेष', 'अखिलेश', 'अवनीश', 'दिलासाराम', 'अगनपाल', 'वीरपाल', 'द्वितीय', 'पक्ष', 'साधू', 'उर्फ', 'गजेन्द्र', 'धर्मवीर', 'गजेन्द्र', 'सुखवीर', 'उर्फ', 'नरवीर', 'चकपाल', 'भानपाल', 'शिवमंगल', 'विवादित', 'जमीन', 'कब्जा', 'उद्देश्य', 'ट्रैक्टरों', 'मय', 'खेती', 'उपकरणों', 'सहितमौजूद', 'पक्ष', 'काफी', 'आकोशित', 'पक्षों', 'वार्ता', 'जानकारी', 'तोदोनों', 'पक्षों', 'पिडारा', 'उत्तर', 'जमीन', 'बताते', 'कब्जा', 'चाह', 'पक्षों', 'समझाने', 'प्रयास', 'लगा', 'पक्ष', 'पार्टी', 'सेआकोशित', 'होकर', 'एकराय', 'होकर', 'गोट', 'छिपे', 'आयुधों', 'निकालकरपुलिस', 'पार्टी', 'मारने', 'नीयत', 'फायरिंग', 'लगे', 'आसपास', 'खेतों', '2में', 'मजदूर', 'बचाकर', 'भाग', 'मौके', 'काफी', 'भय', 'आतंकव्

In [5]:
muslim = {"अब्दुल", "अहमद", "आरिफ", "खां", "खालिद", "नदीम", "मुस्लिम", "मोहम्मद", "रिजवान", "सलीम" }
hindu = {"अमरजीत", "आर्य", "आशीष", "ओमकार", "किशोर", "कुलदीप", "जयराम", "धीरेन्द्र", "नितिन", "मुलायम", "राजपूत", "रामानन्द", "विजयपाल", "विमलेश", "श्रीराम"}

In [6]:
gt_data,gt_label,gt_reli = [],[],[]

In [7]:
for i in range(10000):
  for x in data[i]:
     for y in muslim:
      if(x==y):
        gt_data.append(data[i]);
        gt_label.append(data_label[i])
        gt_reli.append(1)
        break;


     for y in hindu:
      if(x==y):
        gt_data.append(data[i]);
        gt_label.append(data_label[i])
        gt_reli.append(2)
        break;

In [13]:
len(gt_data)
print(gt_data[10])

['पैरोकार', 'हनीफखॉ', 'शपथ', 'समर्थित', 'कथानक', 'अनुसार', 'संक्षेप', 'तथ्य', 'प्रकार', 'हैंकि', 'एसएचओ', 'शेर', 'अछनेरा', 'सूचनारिपोर्ट', '18042019', '1950', 'बजे', 'कथन', 'दर्जकराई', 'सामान्य', 'लोकसभा', 'चुनाव', '2019', 'व्यवस्था', 'ड्यूटीहेतु', 'थानाक्षेत्र', '17716', 'बजे', 'ग्राम', 'कचौरा', 'मेंअनीस', 'परिवारीजनों', 'सहयोग', 'पत्मी', 'सायरा', 'बानों', 'कीइत्या', 'वी', 'ग्राम', 'कचौरा', 'पहुंचे', 'तोसायरा', 'बानों', 'शव', 'अनीस', 'जमीन', 'रखा', 'अनीसके', 'परिवारीजन', 'अनीस', 'पुत्र', 'सम्पत', 'अनीस', 'चाचा', 'अहमद', 'अली', 'पुत्रअल्लाबख्स', 'युसुफ', 'पुत्र', 'अहमद', 'अली', 'अनीस', 'बौना', 'विशेष', 'न्यायाधीश', 'दएप्र0क्षेतर', 'जानत', 'प्र', 'पन', '749720अनीस', 'बनाम', 'राज्यसुनील', 'हनीफ', 'शरीफ', 'पुत्र', 'गण', 'सम्पत', 'गांव', 'गंगाराम', 'पुत्र', 'रूपराम', 'पोहपसिंह', 'पुत्र', 'सभाराम', 'गुङ्डु', 'पुत्र', 'रतनसिंह', 'सत्यप्रकाश', 'पुत्र', 'कुंवरजीपुत्र', 'रनछोर', 'पूर्व', 'संजू', 'पुत्र', 'वीरो', 'पुत्र', 'राजासिंह', 'हरीओमपुत्र', 'प्रसादी', 'पूर्व', 'रमेश', 'पुत्र', 'लोहरे', 'प

# LDA


In [14]:
import gensim
from gensim.models.ldamodel import LdaModel

In [15]:
text_corpus = gt_data

In [16]:
from gensim.corpora.dictionary import Dictionary
from gensim import corpora
# Create a corpus from a list of cleaned sentences

dictionary = corpora.Dictionary(text_corpus)
common_corpus = [dictionary.doc2bow(x) for x in text_corpus]

In [21]:
# common_corpus
len(common_corpus)
# common_corpus[10]

2779

In [22]:
lda = LdaModel(common_corpus, num_topics=85)

In [23]:
lda.save('model.lda')

In [24]:
new_model_lda = gensim.models.LdaModel.load('/content/model.lda')

In [26]:
new_model_lda

In [25]:
lda_vector = []

for text in text_corpus:
  text_vec = [dictionary.doc2bow(text)]
  text_topics = new_model_lda[text_vec]

  temp_topic = []
  for topic in text_topics:
    temp_topic.append(topic)

  lda_vector.append(temp_topic)

In [27]:
# lda_vector
print(len(lda_vector))

2779


In [29]:
for i in range(100,106):
  print(lda_vector[i])

[[(2, 0.03078727), (3, 0.060662847), (7, 0.2683756), (8, 0.24127682), (9, 0.0267162), (47, 0.29073697), (72, 0.060495164)]]
[[(2, 0.030792031), (3, 0.059793163), (7, 0.2684309), (8, 0.24079533), (9, 0.026792353), (47, 0.28771463), (72, 0.057738453)]]
[[(25, 0.18138477), (27, 0.6471762), (30, 0.16032322)]]
[[(1, 0.876011), (11, 0.09392321), (46, 0.02424385)]]
[[(1, 0.85064626), (5, 0.038417563), (11, 0.081921875), (46, 0.02326316)]]
[[(1, 0.8506237), (5, 0.03843451), (11, 0.08193995), (46, 0.023250688)]]


# Clustering 5-cluster

In [30]:
import numpy as np

In [32]:
clustering_data = np.zeros((2779,85),dtype=float)
for i in range(2779):
  for a1 in lda_vector[i]:
    for a,b in a1:
      # print(a)
      # print(b)
      clustering_data[i][a]=b

In [38]:
clustering_data[200]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05655203, 0.33129385, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17468235, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.18499902, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.24986036, 0.        , 0.     

In [39]:
from sklearn.cluster import KMeans

In [40]:
cluster_model = KMeans(n_clusters=5)
clusters = cluster_model.fit_predict(clustering_data)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [41]:
clusters

array([2, 2, 2, ..., 2, 2, 2], dtype=int32)

In [ ]:
# cluster_model.cluster_centers_

In [43]:
cluster_cen = cluster_model.cluster_centers_

# Fairlet balance factor

In [45]:
# for each cluster [muslim, hindu, undetected]
fairlet_cluster_stat = [ [0,0] for _ in range(5)]

In [46]:
for i in range(2779):
  if gt_reli[i] == 1:
    fairlet_cluster_stat[clusters[i]][0] += 1
  elif gt_reli[i] == 2:
    fairlet_cluster_stat[clusters[i]][1] += 1

In [47]:
fairlet_cluster_stat

[[234, 178], [159, 120], [1119, 622], [115, 95], [95, 42]]

In [48]:
balance_factor = 1;
for i in range(5):
  balance_factor = min(balance_factor,
                       min(fairlet_cluster_stat[i][0]/fairlet_cluster_stat[i][1],fairlet_cluster_stat[i][1]/fairlet_cluster_stat[i][0]))

In [49]:
balance_factor

0.4421052631578947

# fair-clustering evaluation, samira samadi

In [58]:
dist_hindu = 0
dist_muslim = 0

In [50]:
for i in range(2779):
  if gt_reli[i]==1:
    x1 = (np.linalg.norm(clustering_data[i] - cluster_cen[clusters[i]]))
    dist_muslim += x1
  elif gt_reli[i]==2:
    x1 = (np.linalg.norm(clustering_data[i] - cluster_cen[clusters[i]]))
    dist_hindu += x1

In [54]:
hindu_num, muslim_num = 0,0
for i in range(len(gt_reli)):
  if gt_reli[i]==1:
    muslim_num +=1
  else :
    hindu_num+=1

In [55]:
dist_hindu/hindu_num

0.5869763217261669

In [57]:
dist_muslim/muslim_num

0.6412429825589918

# Topic most frq topic extraction

In [73]:
frq_topic = np.zeros((5,85))

In [77]:
for i in range(2779):
  frq_topic[clusters[i]-1] = np.add(frq_topic[clusters[i]-1],clustering_data[i] )

In [81]:
frq_topic

array([[6.61444971e-01, 1.04837986e-02, 2.67508599e+00, 3.00351493e+00,
        2.23254538e+00, 5.50398322e+00, 6.74866810e+00, 5.35083460e-01,
        1.73721060e+00, 4.46116419e+00, 4.53096852e-02, 4.64061966e-01,
        1.49834462e-01, 6.61201552e-02, 2.03738521e+00, 3.06482185e-02,
        6.34410306e-01, 1.18906846e-01, 4.54129033e-01, 8.57017322e-01,
        5.54841185e-01, 1.87711144e-01, 5.72816325e+01, 4.97644883e-01,
        1.72551006e+00, 2.40289559e+00, 1.11959287e+00, 1.04888652e+00,
        6.11131638e-02, 1.48275992e+00, 5.65549855e+01, 4.60774824e-02,
        0.00000000e+00, 0.00000000e+00, 1.05027205e+00, 2.50344856e+00,
        6.24166763e-01, 6.88369751e-01, 0.00000000e+00, 0.00000000e+00,
        2.76311484e+00, 5.54673272e-01, 0.00000000e+00, 4.65873631e-01,
        4.43922466e-01, 3.27297534e-01, 1.13147159e-01, 3.69346465e+00,
        5.76315590e+01, 5.66420976e-01, 8.54442613e-01, 2.77186950e+00,
        2.28999272e+00, 2.62256829e-01, 7.61831300e-02, 2.088841