<a href="https://colab.research.google.com/github/routb68/hdlc/blob/main/lda_vector_generation_clustering_fairEvaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data loading

In [1]:
import pickle

In [2]:
with open('/content/drive/MyDrive/Fairness in machine learning/HLDC   LDA preWork/df.pkl', 'rb') as file:
    df = pickle.load(file)

In [3]:
df

label                                           sentence  word_count  \
0         1     ['अभियुक्त इस मामले में जेल में निरुद्ध है। ']           9   
1         0  ['जमानत प्रार्थना पत्र के समर्थन में रहमीना पत...         485   
2         0  ['संक्षेप में अभियोजन कथानक इस प्रकार है कि वा...         517   
3         0  ['जमानत प्रार्थना-पत्र के समर्थन में शपथ-पत्र ...         269   
4         0  ['अभियोजन कहानी के अनुसार वादी मुकदमा पुलिस उप...         625   
...     ...                                                ...         ...   
9995      1  ['04.03.2021यह जमानत प्रार्थना पत्र प्रार्थी /...         604   
9996      0  ['अभियुक्तगण न्यायिक अभिरक्षा में जेल में निरू...         461   
9997      1  ['23.10.2020पत्रावली पेश हुई । प्रार्थी / अभिय...         237   
9998      0  ['इस आवेदन के साथ अभियुक्ता की रिश्तेदार सुलेख...         167   
9999      0  ['फ्ठार्थीगण / अभियुक्तगण न्यायिक अभिरक्षा में...          68   

                                         text_processed  \
0     [[, ', अभियुक्त, इस, मामले, में, जेल, में, निर...   
1     [[, ', जमानत, प्रार्थना, पत्र, के, समर्थन, में...   
2     [[, ', संक्षेप, में, अभियोजन, कथानक, इस, प्रका...   
3     [[, ', जमानत, प्रार्थना, -, पत्र, के, समर्थन, ...   
4     [[, ', अभियोजन, कहानी, के, अनुसार, वादी, मुकदम...   
...                                                 ...   
9995  [[, ', 04032021यह, जमानत, प्रार्थना, पत्र, प्र...   
9996  [[, ', अभियुक्तगण, न्यायिक, अभिरक्षा, में, जेल...   
9997  [[, ', 23102020पत्रावली, पेश, हुई, ।, प्रार्थी...   
9998  [[, ', इस, आवेदन, के, साथ, अभियुक्ता, की, रिश्...   
9999  [[, ', फ्ठार्थीगण, अभियुक्तगण, न्यायिक, अभिरक्...   

                                    text_processed_stop  \
0                       [अभियुक्त, मामले, जेल, निरुद्ध]   
1     [जमानत, प्रार्थना, पत्र, समर्थन, रहमीना, पत्नी...   
2     [संक्षेप, अभियोजन, कथानक, प्रकार, वादी, मुकदमा...   
3     [जमानत, प्रार्थना, पत्र, समर्थन, शपथ, पत्र, इम...   
4     [अभियोजन, कहानी, अनुसार, वादी, मुकदमा, पुलिस, ...   
...                                                 ...   
9995  [04032021यह, जमानत, प्रार्थना, पत्र, प्रार्थी,...   
9996  [अभियुक्तगण, न्यायिक, अभिरक्षा, जेल, निरूद्ध, ...   
9997  [23102020पत्रावली, पेश, प्रार्थी, अभियुक्त, वि...   
9998  [आवेदन, अभियुक्ता, रिश्तेदार, सुलेखा, नाम, काश...   
9999  [फ्ठार्थीगण, अभियुक्तगण, न्यायिक, अभिरक्षा, अभ...   

      word_count_text_processed_stop  \
0                                  4   
1                                292   
2                                306   
3                                154   
4                                363   
...                              ...   
9995                             397   
9996                             273   
9997                             114   
9998                              93   
9999                              30   

                       text_processed_stop_rem_mostfreq  \
0                                 [मामले, जेल, निरुद्ध]   
1     [समर्थन, रहमीना, पत्नी, फैय्याज, शपथपत्र, आशय,...   
2     [संक्षेप, कथानक, प्रकार, पाण्डेयपुत्र, स्व0, द...   
3     [समर्थन, शपथ, इमरान, पुत्रमुखिया, उर्फ, मुजाफि...   
4     [कहानी, अनुसार, उपनिरीक्षक, श्रीअरविन्द, 24062...   
...                                                 ...   
9995  [द्वाराउपरोक्त, संख्या, ह़ै, शपथ, समर्थित, मय,...   
9996  [न्यायिक, अभिरक्षा, जेल, निरूद्ध, कथानक, अनुसा...   
9997  [पेश, समक्ष, यहतक, प््रार्थीअभियुक्त, निर्दोष,...   
9998  [आवेदन, अभियुक्ता, रिश्तेदार, सुलेखा, काशपथपत्...   
9999  [न्यायिक, अभिरक्षा, कहाहै, प््रार्थीगण, निर्दो...   

      word_count_text_processed_stop_rem_mostfreq  \
0                                               3   
1                                             214   
2                                             205   
3                                              99   
4                                             303   
...                                           ...   
9995                                          269   
9996                                 

In [4]:
text_corpus = df['sentence_cleaned_split']

In [5]:
text_corpus[10]

['न्यायिक',
 'अभिरक्षा',
 'निरूद्धहैं',
 'कथन',
 'निर्दोष',
 'मजदूरी',
 'दिल्ली',
 'चला',
 'गयाथा',
 'गैर',
 'जमानतीय',
 'वारन्ट',
 'जारीकर']

# Gensim LDA

In [6]:
import gensim
from gensim.models.ldamodel import LdaModel

In [7]:
from gensim.corpora.dictionary import Dictionary
from gensim import corpora
# Create a corpus from a list of cleaned sentences

dictionary = corpora.Dictionary(text_corpus)
common_corpus = [dictionary.doc2bow(x) for x in text_corpus]

In [8]:
# common_corpus
len(common_corpus)

10000

In [9]:
lda = LdaModel(common_corpus, num_topics=85)

# LDA Model saving

In [10]:
lda.save('model.lda')

In [11]:
new_model_lda = gensim.models.LdaModel.load('/content/model.lda')

In [12]:
# cor = text_corpus[9]

In [13]:
# cor_vec = [dictionary.doc2bow(cor)]
# new_topics = new_model_lda[cor_vec]

# for topic in new_topics:

#       print(topic)

# Lda vector generation

In [14]:
lda_vector = []

for text in text_corpus:
  text_vec = [dictionary.doc2bow(text)]
  text_topics = new_model_lda[text_vec]

  temp_topic = []
  for topic in text_topics:
    temp_topic.append(topic)

  lda_vector.append(temp_topic)

In [15]:
# lda_vector
print(len(lda_vector))

10000


In [16]:
lda_vector[100]

[[(22, 0.5751854), (47, 0.1415329), (74, 0.24560675), (77, 0.01388372)]]

# lda-vec to clustering data

In [17]:
import numpy as np

In [18]:
clustering_data = np.zeros((10000,85),dtype=float)

In [19]:
for i in range(10000):
  for a1 in lda_vector[i]:
    for a,b in a1:
      # print(a)
      # print(b)
      clustering_data[i][a]=b

In [20]:
clustering_data[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.75293285,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

# Clustering KMeans

In [21]:
from sklearn.cluster import KMeans

In [22]:
cluster_model = KMeans(n_clusters=85)
clusters = cluster_model.fit_predict(clustering_data)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [83]:
clusters

array([32, 61, 78, ..., 73, 61, 24], dtype=int32)

In [23]:
cluster_model.cluster_centers_

array([[ 8.07093682e-04,  2.40222159e-03,  1.24639762e-03, ...,
         2.68610637e-04,  1.55947175e-02,  3.05853786e-03],
       [ 3.85512931e-03,  8.59590368e-03,  3.81249523e-04, ...,
         4.86064111e-04,  5.33787599e-03,  4.16228603e-03],
       [ 1.53109365e-03,  9.24950466e-04,  3.25260652e-19, ...,
         3.91088093e-04,  2.47665149e-03,  1.61484496e-03],
       ...,
       [-4.33680869e-19,  5.20417043e-18,  3.25260652e-19, ...,
         4.33680869e-19,  0.00000000e+00, -4.33680869e-19],
       [ 2.16840434e-19,  0.00000000e+00,  1.08420217e-19, ...,
         1.08420217e-19,  0.00000000e+00,  4.33680869e-19],
       [ 4.11457934e-03,  2.09763259e-02,  2.16840434e-19, ...,
         5.42101086e-19,  5.32209196e-04,  1.76042996e-04]])

In [30]:
cluster_cen = cluster_model.cluster_centers_

In [24]:
muslim = {"अब्दुल", "अहमद", "आरिफ", "खां", "खालिद", "नदीम", "मुस्लिम", "मोहम्मद", "रिजवान", "सलीम" }
hindu = {"अमरजीत", "आर्य", "आशीष", "ओमकार", "किशोर", "कुलदीप", "जयराम", "धीरेन्द्र", "नितिन", "मुलायम", "राजपूत", "रामानन्द", "विजयपाल", "विमलेश", "श्रीराम"}

In [25]:
# temp1 = num of muslim,  temp2 = num of hindu
temp1 ,temp2 = 0,0
cnt = [0 for i in range(10000)]
for i in range(10000):
  for x in df['sentence_cleaned_split'][i]:
    for y in muslim:
      if(x==y):
        # print(i)
        temp1+=1
        cnt[i]=1
        break

    for y in hindu:
      if(x==y):
        # print(i)
        cnt[i]=2
        temp2+=1
        break


print(cnt)

[0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 

In [27]:
print("hindu num ",temp2)
print("muslim num ",temp1)

hindu num  1057
muslim num  1722


# fair-clustering evaluation, samira samadi

In [40]:
dist_hindu = 0
dist_muslim = 0

In [41]:
for i in range(len(cnt)):
  if cnt[i]==1:
    x1 = (np.linalg.norm(clustering_data[i] - cluster_cen[clusters[i]]))
    dist_muslim += x1
  elif cnt[i]==2:
    x1 = (np.linalg.norm(clustering_data[i] - cluster_cen[clusters[i]]))
    dist_hindu += x1

In [44]:
dist_hindu/temp2

0.137860437596449

In [45]:
dist_muslim/temp1

0.1136610909973901

# fair-clusstering evaluation, fairlet decomposition

In [82]:
# for each cluster [muslim, hindu, undetected]
fairlet_cluster_stat = [ [0,0,0] for _ in range(85)]

In [84]:
for i in range(10000):
  if cnt[i] == 1:
    fairlet_cluster_stat[clusters[i]][0] += 1
  elif cnt[i] == 2:
    fairlet_cluster_stat[clusters[i]][1] += 1
  else :
    fairlet_cluster_stat[clusters[i]][2] += 1

In [86]:
fairlet_cluster_stat

[[4, 1, 243],
 [47, 36, 281],
 [1, 0, 55],
 [14, 15, 177],
 [13, 18, 124],
 [2, 2, 79],
 [29, 11, 212],
 [18, 13, 217],
 [25, 18, 176],
 [0, 0, 120],
 [16, 12, 131],
 [13, 16, 157],
 [22, 11, 163],
 [14, 8, 35],
 [8, 12, 129],
 [6, 2, 76],
 [0, 0, 36],
 [20, 10, 99],
 [15, 5, 138],
 [6, 2, 62],
 [1, 7, 77],
 [3, 1, 86],
 [7, 13, 75],
 [0, 0, 81],
 [16, 11, 116],
 [11, 6, 91],
 [1, 1, 42],
 [10, 11, 116],
 [2, 2, 74],
 [26, 10, 68],
 [0, 0, 47],
 [9, 8, 66],
 [2, 1, 361],
 [20, 19, 267],
 [6, 1, 58],
 [5, 4, 312],
 [6, 12, 167],
 [1, 3, 32],
 [0, 0, 29],
 [7, 6, 77],
 [5, 4, 40],
 [11, 9, 156],
 [20, 16, 127],
 [16, 28, 219],
 [0, 0, 10],
 [6, 3, 85],
 [17, 14, 88],
 [2, 1, 36],
 [7, 5, 56],
 [3, 1, 17],
 [4, 11, 82],
 [5, 3, 69],
 [9, 4, 80],
 [7, 4, 71],
 [15, 4, 96],
 [0, 0, 26],
 [8, 10, 118],
 [4, 1, 35],
 [7, 3, 55],
 [9, 6, 179],
 [6, 2, 84],
 [28, 19, 207],
 [9, 5, 205],
 [8, 17, 126],
 [5, 5, 26],
 [0, 0, 6],
 [3, 2, 67],
 [30, 14, 139],
 [6, 1, 20],
 [0, 0, 19],
 [14, 4, 94],
